services:
  - type: web
    name: ml-checker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    workingDirectory: backend
    envVars:
      - key: APP_ENV
        value: production
